--Recreate Tweet table as column store
DROP TABLE TWEET;
CREATE COLUMN TABLE TWEET ("ID" BIGINT, "DATE" TIMESTAMP, "CONTENT" NVARCHAR(255), PRIMARY KEY ("ID"));

--Create index with Fulltext search
DROP FULLTEXT INDEX TWEET_FULLTEXT_INDEX;
CREATE FULLTEXT INDEX TWEET_FULLTEXT_INDEX ON TWEET("CONTENT") TEXT ANALYSIS ON CONFIGURATION 'EXTRACTION_CORE';

--Create View for Hashtags
DROP VIEW "TRANSACTIONS_VIEW";
CREATE VIEW "TRANSACTIONS_VIEW" AS
SELECT "$TA_TWEET_FULLTEXT_INDEX".ID, TA_TOKEN as TOKEN FROM "$TA_TWEET_FULLTEXT_INDEX"
INNER JOIN TWEET ON "$TA_TWEET_FULLTEXT_INDEX".ID = TWEET.ID
WHERE TA_TYPE = 'SOCIAL_MEDIA/TOPIC_TWITTER';

--Create Apriori Input Type
DROP TYPE PAL_DATA_T;
CREATE TYPE PAL_DATA_T AS TABLE(
"ID" INT,
"TOKEN" VARCHAR(100)
);

--Create Apriori Output Type
DROP TYPE PAL_RESULT_T;
CREATE TYPE PAL_RESULT_T AS TABLE(
"PRERULE" VARCHAR(500),
"POSTRULE" VARCHAR(500),
"SUPPORT" DOUBLE,
"CONFIDENCE" DOUBLE,
"LIFT" DOUBLE
);

--Create Apriori PMML Type
DROP TYPE PAL_PMMLMODEL_T;
CREATE TYPE PAL_PMMLMODEL_T AS TABLE(
"ID" INT,
"PMMLMODEL" VARCHAR(5000)
);

--Create Apriori Control Type
DROP TYPE PAL_CONTROL_T;
CREATE TYPE PAL_CONTROL_T AS TABLE(
"NAME" VARCHAR (50),
"INTARGS" INTEGER,
"DOUBLEARGS" DOUBLE,
"STRINGARGS" VARCHAR (100)
);

--Create Apriori Result Table
DROP TABLE APRIORI_RESULT;
CREATE COLUMN TABLE APRIORI_RESULT(
"PRERULE" VARCHAR(500),
"POSTRULE" VARCHAR(500),
"SUPPORT" Double,
"CONFIDENCE" Double,
"LIFT" DOUBLE
);

--Create Apriori PMML Table
DROP TABLE APRIORI_PMML_MODEL;
CREATE COLUMN TABLE APRIORI_PMML_MODEL (
"ID" INT,
"PMMLMODEL" VARCHAR(5000)
);

--Create Apriori Procedure Input and Output Map Table
DROP TABLE PDATA;
CREATE COLUMN TABLE PDATA(
"POSITION" INT,
"SCHEMA_NAME" NVARCHAR(256),
"TYPE_NAME" NVARCHAR(256),
"PARAMETER_TYPE" VARCHAR(7)
);

--Setup Apriori Procedure Input and Output Map Table params
INSERT INTO PDATA VALUES (1, CURRENT_USER, 'PAL_DATA_T', 'IN');
INSERT INTO PDATA VALUES (2, CURRENT_USER, 'PAL_CONTROL_T', 'IN');
INSERT INTO PDATA VALUES (3, CURRENT_USER, 'PAL_RESULT_T', 'OUT');
INSERT INTO PDATA VALUES (4, CURRENT_USER, 'PAL_PMMLMODEL_T', 'OUT');

--Create Apriori Procedure
CALL SYS.AFLLANG_WRAPPER_PROCEDURE_DROP('SYSTEM', 'PAL_APRIORI_RULE');
CALL SYS.AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL', 'APRIORIRULE', 'SYSTEM', 'PAL_APRIORI_RULE', PDATA);

--Create Apriori Config Table
DROP TABLE APRIORI_PROCEDURE_CONFIGURATION;
CREATE COLUMN TABLE APRIORI_PROCEDURE_CONFIGURATION(
"NAME" VARCHAR (50),
"INTARGS" INTEGER,
"DOUBLEARGS" DOUBLE,
"STRINGARGS" VARCHAR (100)
);

--Configure Apriori procedure
INSERT INTO APRIORI_PROCEDURE_CONFIGURATION VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO APRIORI_PROCEDURE_CONFIGURATION VALUES ('MIN_SUPPORT', null, 0.02, null);
INSERT INTO APRIORI_PROCEDURE_CONFIGURATION VALUES ('MIN_CONFIDENCE', null, 0.02, null);

--Create Cleanup Procedure
DROP PROCEDURE SYSTEM.CLEANUP;
CREATE PROCEDURE SYSTEM.CLEANUP language SQLSCRIPT as
BEGIN
	DELETE FROM TWEET CASCADE;
	DELETE FROM APRIORI_RESULT;
END;






