DROP PROCEDURE SYSTEM.CLEANUP;
CREATE PROCEDURE SYSTEM.CLEANUP language SQLSCRIPT as
BEGIN
	DELETE FROM TWEET CASCADE;
	DELETE FROM "$TA_TWEET_FULLTEXT_INDEX";
	DELETE FROM APRIORI_RESULT;
END;

DROP PROCEDURE SYSTEM.APRIORI;
CREATE PROCEDURE SYSTEM.APRIORI language SQLSCRIPT as
BEGIN
	CALL SYSTEM.PAL_APRIORI_RULE(TRANSACTIONS_VIEW, APRIORI_PROCEDURE_CONFIGURATION, APRIORI_RESULT, APRIORI_PMML_MODEL) WITH OVERVIEW;
END;


